server:
  port: 8080
  servlet:
    context-path: /api



spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/NGT_NEW
    username: postgres
    password: postgres
  jpa:
    show-sql: true


