server:
  port: 8080
  servlet:
    context-path: /api



spring:
  datasource:
    url: jdbc:postgresql://localhost:8000/NGT_NEW2
    username: postgres
    password: 1234
  jpa:
    show-sql: true


